:set autoindent
:set tabstop=4
:set shiftwidth=4
:set smarttab
:set softtabstop=4
:set number
:set relativenumber
:set cursorline
:set ignorecase
nmap Q <nop>
autocmd InsertEnter * let @/=''
nnoremap <CR> i<Escape>l
