:set autoindent
:set tabstop=4
:set shiftwidth=4
:set smarttab
:set softtabstop=4
:set number
:set relativenumber
:set cursorline
:set ignorecase
nmap Q <nop>
autocmd InsertEnter * let @/=''
nnoremap <CR> i<Escape>l
nnoremap n nzz
nnoremap N Nzz
nnoremap <C-o> <C-o>zz
nnoremap <C-i> <C-i>zz
vnoremap <Enter> y
nnoremap <M-y> "+y
vnoremap <M-y> "+y
