#!/usr/bin/env bash

set -e

if test -f "$HOME/.remote_indicator"; then
	CONFIG="remote.conf.yaml"
else
	CONFIG="install.conf.yaml"
fi

echo "CONFIG: $CONFIG"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
