#!/bin/sh

# Backup dconf
echo "Backing up gnome/config.dconf"
dconf dump / | sed "/picture-uri=/d;/org\/gtk\/settings\/color-chooser/d;/selected-color=/d" | cat -s > gnome/config.dconf
git add gnome/config.dconf

# Backup vscode extension
code --list-extensions > editors/vscode/extensions
git add editors/vscode/extensions

### Filter editors/vscode/settings.json
# backup first
cp editors/vscode/settings.json /tmp/vscode-settings.json
sed -i "/email/d" editors/vscode/settings.json
git add editors/vscode/settings.json
cp /tmp/vscode-settings.json editors/vscode/settings.json
