#!/usr/bin/env bash

set -e

WORKTREES_ROOT="$HOME/worktrees"
BRANCH_PREFIX=""

print_usage()
{
	echo "usage: git new-session <branch name> [jira proj name]"
	exit 0
}

if [[ $@ == *'-h'* ]]; then
	print_usage
fi

if [ "$#" -lt 1 ]; then
	print_usage
fi

git_root=$(git rev-parse --show-toplevel)
if [[ $? != 0 ]]; then
	exit 1
fi
PROJ_NAME=$(basename "$git_root")
WORKTREE_PATH="$WORKTREES_ROOT/$PROJ_NAME/$1"

read -p "Confirm worktree path '$WORKTREE_PATH'? [y/N] " answer
[[ "$answer" =~ ^[Yy]$ ]] || exit 1

BRANCH_NAME=$BRANCH_PREFIX$1
read -p "Confirm branch name '$BRANCH_NAME'? [y/N] " answer
[[ "$answer" =~ ^[Yy]$ ]] || exit 1

TMUX_SESSION_NAME="$PROJ_NAME-$1"
read -p "Confirm tmux session name '$TMUX_SESSION_NAME'? [y/N] " answer
[[ "$answer" =~ ^[Yy]$ ]] || exit 1

mkdir -p "$WORKTREES_ROOT/$PROJ_NAME/"
git worktree add "$WORKTREE_PATH" -b $BRANCH_NAME

cd "$WORKTREE_PATH"
git reset --hard origin/main

if [ -z $TMUX ]; then
	tmux new-session -s "$PROJ_NAME-$1" -c "$WORKTREE_PATH"
else
	unset TMUX
	attach=false # dont attach to nested tmux just create the session
	tmux new-session -d -s "$PROJ_NAME-$1" -c "$WORKTREE_PATH"
fi
