#!/usr/bin/env bash

set -e

source ~/dotfiles_scripts/helpers/prompt.sh
WORKTREES_ROOT="$HOME/worktrees"

print_usage() {
	echo "usage: git delete-session <branch name>"
	exit 0
}

if [[ $@ == *'-h'* ]]; then
	print_usage
fi

if [ "$#" -lt 1 ]; then
	if [ ! -z $TMUX ]; then # Attach on remote (smux)
		tmux_session=$(tmux display-message -p '#S')
		PROJ_NAME=$(echo "$tmux_session" | sed 's/-.*//g')
		if yes_no "Delete current tmux session ($tmux_session)"; then
			branch_name=$(echo "$tmux_session" | sed "s/$PROJ_NAME-//")
		else
			exit
		fi
	else
		print_usage
	fi
else
	git_root=$(git rev-parse --show-toplevel)
	if [[ $? != 0 ]]; then
		echo "not in a git dir"
		exit 1
	fi

	PROJ_NAME=$(basename "$git_root")
	branch_name=$1
fi

WORKTREE_PATH="$WORKTREES_ROOT/$PROJ_NAME/$branch_name"

if ! ls $WORKTREES_ROOT/$PROJ_NAME | grep -o $branch_name >/dev/null; then
	echo "Didnt find $WORKTREES_ROOT/$PROJ_NAME/$branch_name"
	exit 1
fi

if ! yes_no "Delete $WORKTREE_PATH worktree and kill $PROJ_NAME-$branch_name session"; then
	exit
fi

git worktree remove "$WORKTREE_PATH"
tmux kill-session -t "$PROJ_NAME-$branch_name"
