#!/bin/bash

FONT=pagga

PWD="$(pwd)"
DEPLOY_DIR="$HOME/dotfiles_scripts/deploy/"
GIT_ROOT="$(git rev-parse --show-toplevel 2> /dev/null)"
FILES_IN_GIT_ROOT="$(ls $GIT_ROOT)"

echo "WD: $PWD"
echo ""

DEPLOYER=""

if test -f ./deploy; then
    DEPLOY_DIR=.
elif test -f ./go.mod; then
    DEPLOYER=go
elif test -f ./main.go; then
    DEPLOYER=go
elif echo "$PWD" | grep -q "volumez"; then
    DEPLOYER=volumez
elif echo "$PWD" | grep -q "$HOME/playgrounds/"; then
    DEPLOYER=playground
elif echo "$FILES_IN_GIT_ROOT" | grep -q "Cargo\.toml"; then
    DEPLOYER=rust
    DEPLOYER=deploy
else
    echo "Deploy script for this folder not found"
    echo "Press any key to continue..."
    read -n 1
    exit
fi

# toilet --gay "${DEPLOYER^^}" --font=$FONT

$DEPLOY_DIR/$DEPLOYER $@
exitcode=$?

echo ""
if [ $exitcode -eq 0 ]; then
    toilet --metal "DONE" --font=$FONT
else
    printf "\e[91m"
    toilet "FAILED" --font=$FONT
fi
# echo "Press any key to continue..."
read -n 1
