#!/usr/bin/env bash

if test -f "$HOME/.remote_indicator"; then
	"$HOME/dotfiles_scripts/inner/osc52_yank.sh" <&0
elif command -v clip.exe &> /dev/null; then
	clip.exe
elif [ "$XDG_SESSION_TYPE" = "wayland" ]; then
	wl-copy
else
	xclip -sel clip <&0
fi
