#!/bin/sh

echo "=== VOLUMEZ UT DEPLOY ==="

HOST="${1:-rhel8-5.local}"
echo "Host: $HOST"
rm *\.test
echo "Building..."
go test -c -gcflags "all=-N -l"
echo "Delivering..."
scp *\.test root@$HOST:~/
