#!/usr/bin/env bash

if command -v powershell.exe &> /dev/null; then
	powershell.exe $(wslpath -m ~/dotfiles_scripts/notify/windows_notify.ps1) $@
else
	notify-send.sh $@
	paplay /usr/share/sounds/freedesktop/stereo/network-connectivity-established.oga
fi
