#!/usr/bin/env bash

HOST="${1:-rhel8-5.local}"

tmux split-window -h -l 35% "ssh -t root@$HOST '/usr/bin/watch -n0.2 cat /proc/mdstat'"
tmux split-window -v -l 66% "ssh -t root@$HOST '/usr/bin/watch -n0.2 lsblk -s'"
tmux split-window -v -l 50% "ssh -t root@$HOST '/usr/bin/watch -n0.2 free -m'"

tmux select-pane -t 1

rssh root@$HOST
